### ISSUE TITLE
Script to populate tags in a repository

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/ethereum-python-project-template#15]
We should use the tag structure that is used in py-evm everywhere and we should have a script that can be used to inject those tags into a given github repository via the github API.

**Comment by pipermerriam** [comment]
@cburgdorf did you script what you did with py-evm?

**Comment by cburgdorf** [comment]
Nope, but this works well https://github.com/jvandemo/copy-github-labels

**Comment by pipermerriam** [comment]
:+1: cool, so maybe we can wrap that in some way or at least provide the correct commands to initialize a new repository.

**Comment by pacrob** [comment]
Closing as old, feel free to reopen with more context if it's still relevant
