### ISSUE TITLE
Consider alternative way of defining extras

### ISSUE THREAD

**Issue by carver** [ethereum/ethereum-python-project-template#17]
When we have some extras that are unions of other extras (like `dev`), there is no awesome solution.

Instead of building a dict of extras, and composing them programatically in the setup.py, one option would be to use a setup.cfg like: https://github.com/pypa/setuptools/issues/1260#issuecomment-438187625

- pros
  - It seems cleaner to read & understand
  - It might be an "officially preferred" way to do it (soon)
- cons
  - adds a lot of package churn for minor impact
  - adds another file to the root directory
  - it is so new, that it might stop being preferred pretty soon. don't want to jump on the bandwagon too soon

This issue is mostly to remember that there's another option, and maybe review again in 6-12 months.

**Comment by pacrob** [comment]
`setup.cfg` seems to be going away, with `pyproject.toml` here to stay. At some point we will migrate from a `setup.py` to `pyproject.toml`, and this concern will be handled.
