### ISSUE TITLE
Split makefile in two: build wheel, then push/release

### ISSUE THREAD

**Issue by carver** [ethereum/ethereum-python-project-template#18]
## What was wrong?

Occasionally, problems are not detected until the project is packaged up for release. See https://github.com/ethereum/py-evm/issues/1608

The current `make release` means that testing a fix to a broken release like ^ is painful and error-prone.

### Preventing bad releases

Split the Makefile into:
1. `make package`
  - cleans and builds the package
  - prints the command to pip install the newly built wheel
2. `make release bump="..."`
  - bumps the version
  - pushes commits/tags to master
  - `twine upload`

Implicitly in between the steps (which I suppose *explicitly* belongs in: https://github.com/ethereum/snake-charmers-tactical-manual/blob/master/cutting-a-release.md ) is installing the package into a local virtualenv and "smoke testing". ie~ making sure some basic functionality of the package works

---

### Dealing with busted releases

- Also, add a new `make revert-release commit="a1b2c3..."` which tags an old commit with a new version number, pushes the tag up, and uploads via twine.
- Note that at least some repos, like py-evm won't let you push that change to master (would require a force-push). That reverted version will just never make it into the master branch, which seems acceptable.
- Finally, note that you can reuse `make package` to re-test the old build by just checking out to the old commit you want. (although this *should* be super redundant testing)

**Comment by carver** [comment]
As per usual with the template project, it's best to actually try the changes in a live project, before making them to the general repo. So I'll start with py-evm/trinity and if we are happy with the changes after the next release, I'll port them into the general template.

**Comment by carver** [comment]
Let's watch this change go through at least one release cycle on py-evm/trinity before pushing to the template: https://github.com/ethereum/py-evm/pull/1630

It might even be reasonable to generalize this package test to all repos: https://github.com/ethereum/py-evm/pull/1643

**Comment by pacrob** [comment]
It doesn't look like this was actually ever applied to py-evm? Releases are going fine afaik, closing as unnecessary.

**Comment by carver** [comment]
FWIW, this was implemented as `make package` in py-evm:
https://github.com/ethereum/py-evm/blob/72bb43ed06fba51e2408101bf3ae510ff4ca1937/Makefile#L56-L58
https://py-evm.readthedocs.io/en/latest/contributing.html#final-test-before-each-release

Obviously make your own choices, but it did help find issues sometimes in my experience :)

**Comment by pacrob** [comment]
Thanks for the pointer, will review on the next go-round.

**Comment by carver** [comment]
One example of something that `make package` and smoke testing could notice is:

if the setup.py was missing a library that was necessary for the main project to run, but the problem was hidden because one of the testing tools requires the same library, so the testing environment loads without a problem. (also, all the dev environments would have the library loaded)
