### ISSUE TITLE
Add Apache as a default license option

### ISSUE THREAD

**Issue by carver** [ethereum/ethereum-python-project-template#32]
We can't retroactively apply Apache without contributor consent, but new projects should probably be at least dual-licensed with Apache.

**Comment by davesque** [comment]
I've seen this dual Apache/MIT license thing in a couple of places now.  What's the reasoning behind that?

**Comment by carver** [comment]
There was a conversation in AllCoreDevs that reminded me of the difference from MIT: It's got a kind of mutual agreement not to sue over software patents.

> The Apache License 2.0 makes sure that the user does not have to worry about infringing any patents by using the software. The user is granted a license to any patent that covers the software. This license is terminated if the user sues anyone over patent infringement related to this software. This condition is added in order to prevent patent litigations.

~[wikipedia](https://en.wikipedia.org/wiki/Apache_License)

**Comment by davesque** [comment]
Yeah, that sounds like a definite win.

**Comment by pacrob** [comment]
Closing as old. The reasoning makes sense, but I feel like it could make it confusing especially if a new Apache-licensed library were to become a dependency of an MIT one. Open to discussing if strong feelings still exist.
