### ISSUE TITLE
Add flake8-bugbear

### ISSUE THREAD

**Issue by carver** [ethereum/ethereum-python-project-template#35]
I'm guessing it follows semver, given the major version number

Maybe add a note about flake8 in setup.py, like:
```py
        "flake8==3.7.9",  # flake8 is not semver: it has added new warnings at minor releases
```

(unrelated: add same note to mypy)

**Comment by pacrob** [comment]
Closing as old. mypy and flake8 are kept pinned in most places.

**Comment by carver** [comment]
Since the example warning comment I gave wasn't convincing, maybe it needs to address that flake8 *claims* semver. Something like:

```
        "flake8==3.7.9",  # although flake8 follows semver for their API, it adds new warnings at minor releases. That breaks in-flight PRs on minor flake8 releases, so we pin it
