### ISSUE TITLE
Add platforms keyword to setup.py

### ISSUE THREAD

**Issue by carver** [ethereum/ethereum-python-project-template#37]
eg~

```py
platforms=["unix", "linux", "osx"],
```

**Comment by davesque** [comment]
Wow, I have been duck-duck-going around for a while now and I can't for the life of me find anything that says what platforms are valid in that argument or how that metadata is used.  I've even been poking around in the `setuptools` and `distutils` source code and still can't find anything.

The general meaning is clear but I thought it would be good to know exactly what a person is saying about their package if they claim they support unix.

**Comment by carver** [comment]
I *didn't* pull this from the docs, so it's possible that it's deprecated or even just wrong. I saw it in the libp2p setup.py, which I think pulled from the py-ecc one.

**Comment by carver** [comment]
Hm, looks like the better option is to add a classifier anyway: https://stackoverflow.com/a/34994245
