### ISSUE TITLE
Review development setup section of readme instructions

### ISSUE THREAD

**Issue by carver** [ethereum/ethereum-python-project-template#38]
For example:

- Drop pandoc from the readme
- If `when-changed` is a recommended option, then make sure its installed in the `[dev]` extra
- Add releasing instructions to default docs
- link to releasing instructions there ^ instead of leaving it in the README
- etc...

**Comment by pacrob** [comment]
Initial cleanup happening in PR #76. Default docs need significantly more love than just a lonely releasing instructions section, so I'll let this close and open a new PR for default docs update.

**Comment by pacrob** [comment]
Closed by #76
