### ISSUE TITLE
requirements-docs.txt installs released version of package

### ISSUE THREAD

**Issue by carver** [ethereum/ethereum-python-project-template#40]
I expect the requirements-docs.txt with this:
```
<PYPI_NAME>[doc]
```
will try to install the *remote, released* version of the package, rather than the locally checked-out one, but I haven't confirmed.

Maybe it should be changed to:
```
.[doc]
```

**Comment by carver** [comment]
Need to try this on an active project before pushing to the template.

**Comment by pacrob** [comment]
Use of `.readthedocs.yml` allows removal of `requirements_docs.txt`, tested here: https://github.com/ethereum/eth-abi/pull/204
