### ISSUE TITLE
Handle dependencies that aren't available on readthedocs

### ISSUE THREAD

**Issue by carver** [ethereum/ethereum-python-project-template#41]
## What was wrong?

It's pretty common to have a project that won't build on RTD because of a dependency that needs some system library. You'll get something like:
```
  building 'fastecdsa.curvemath' extension
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/src
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Isrc/ -I/home/docs/.pyenv/versions/3.7.3/include/python3.7m -c src/curveMath.c -o build/temp.linux-x86_64-3.7/src/curveMath.o -O2
  In file included from src/curveMath.c:1:0:
  src/curveMath.h:6:10: fatal error: gmp.h: No such file or directory
   #include <gmp.h>
            ^~~~~~~
  compilation terminated.
  error: command 'gcc' failed with exit status 1
```

## How can it be fixed?

Add some boilerplate for:
- excluding the dependency from readthedocs builds, like this: https://github.com/libp2p/py-libp2p/blob/7466ace0b831ad45bbeba6179c663edc73b74322/setup.py#L64-L68
- adding a mock in conf.py, as recommended here: https://docs.readthedocs.io/en/rel/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules

Here's an example: https://github.com/libp2p/py-libp2p/pull/370

**Comment by pacrob** [comment]
RTD faq doc is now here: https://docs.readthedocs.io/en/stable/faq.html#why-do-i-get-import-errors-from-libraries-depending-on-c-modules

**Comment by pacrob** [comment]
Closing as old. I looked through libs we maintain and found none that require this mocking. If there are still strong feelings about adding it, we can talk.
